### PR TITLE
Update send email documentation

### PR DESCRIPTION
**Pull request by maxSupermoney**
The documentation for sending emails to a contact is incorrect.

### CODE REVIEW

**Comment by isleshocky77** [comment]
@maxSupermoney Didn't mean to step on your toes; however, I found your PR after submitting mine #56. The bigger issue I had found was that there is an undocumented feature of the "Send Email to Contact" API. I found it when I went to go create the feature.

**Comment by escopecz** [comment]
@isleshocky77 undocumented? https://developer.mautic.org/#send-email-to-contact

**Comment by isleshocky77** [comment]
@escopecz Correct, check out my PR #56. It doesn't currently document that you can sent "tokens" to it to be substituted into the email being sent. This is huge and extremely useful. I was actually going to implement the feature and found it already existed.

**Comment by escopecz** [comment]
Aha, you didn't wrote the token part. I'll close this PR in favor of https://github.com/mautic/developer-documentation/pull/56 since it contains the tokens docs. But thanks @maxSupermoney!

**Pull request closed without merging**
