### PR TITLE
Feature/webhook authenticity verification

### PR DESCRIPTION
**Pull request by Clement134**
Add documentation for webhook authenticity verification and fix some typos in webhook documentation.

### CODE REVIEW

**Comment by escopecz** [comment]
Could you add the JS example from the PR to the docs? I bet it would help a lot.

**Comment by Clement134** [comment]
Thanks @escopecz  for the feedback.
I have added my JS example to the documentation, and completed the existing PHP example with webhook verification.

**Comment by npracht** [comment]
PR is closed on mautic/mautic

**Comment by alanhartless** [comment]
This should be re-opened and merged since the feature was merged into M3 right? https://github.com/mautic/mautic/pull/6867#issuecomment-660261095

**Pull request merged**
